package xd.fw.bean.mapper;

import org.apache.ibatis.annotations.Param;
import xd.fw.bean.Dzlist;

import java.util.List;

public interface DzlistMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_dzlist
	 * @mbggenerated
	 */
	int insert(Dzlist record);

	List<Dzlist> selectDzlists(@Param("dzlist")Dzlist dzlist,@Param("start")int start, @Param("limit")int limit);

	int getDzListCount(Dzlist dzlist);

	List<Dzlist> selectDzlistsByYearAndMonth(@Param("wxid")String wxid
			, @Param("year")int year, @Param("month")int month);

    void updateDzlistStatus(Dzlist dzlist);

	int deleteDzlistForImport(Dzlist dzlist);

	int deleteDzlitByYearAndMonth(@Param("year")int year, @Param("month")int month);

	List<Dzlist> selectAllDzlisWithUser(@Param("year")int year, @Param("month")int month);

	int updateDzListAutomatic();
}