package xd.fw.bean.mapper;

import xd.fw.bean.Grade;

import java.util.List;

public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grade
     *
     * @mbggenerated
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grade
     *
     * @mbggenerated
     */
    int insertSelective(Grade record);

    List<Grade> selectReports();
}