package xd.fw.bean.mapper;

import org.apache.ibatis.annotations.Param;
import xd.fw.bean.Mod;

import java.util.List;

public interface ModMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mod
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mod
     *
     * @mbggenerated
     */
    int insert(Mod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mod
     *
     * @mbggenerated
     */
    int insertSelective(Mod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mod
     *
     * @mbggenerated
     */
    Mod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mod
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mod
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mod record);

    List<Mod> selectUserMods(@Param("userId")Integer userId);

    List<Mod> selectModByRole(@Param("roleId")Integer roleId);
}