package xd.fw.bean.mapper;

import xd.fw.bean.PrimaryKey;

public interface PrimaryKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_primary_key
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_primary_key
     *
     * @mbggenerated
     */
    int insert(PrimaryKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_primary_key
     *
     * @mbggenerated
     */
    int insertSelective(PrimaryKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_primary_key
     *
     * @mbggenerated
     */
    PrimaryKey selectByPrimaryKey(String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_primary_key
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrimaryKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_primary_key
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrimaryKey record);
}