package xd.fw.bean.mapper;

import xd.fw.bean.RoleMod;

public interface RoleModMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolemod
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolemod
     *
     * @mbggenerated
     */
    int insert(RoleMod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolemod
     *
     * @mbggenerated
     */
    int insertSelective(RoleMod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolemod
     *
     * @mbggenerated
     */
    RoleMod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolemod
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleMod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolemod
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleMod record);
}