package xd.fw.bean;

import java.util.Date;

public class EnterOrOutRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjc_enterorout_record.Order_num
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjc_enterorout_record.Car_number
     *
     * @mbggenerated
     */
    private String carNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjc_enterorout_record.Enter_or_Out
     *
     * @mbggenerated
     */
    private Integer enterOrOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjc_enterorout_record.Enter_time
     *
     * @mbggenerated
     */
    private Date enterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjc_enterorout_record.Out_time
     *
     * @mbggenerated
     */
    private Date outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjc_enterorout_record.Price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjc_enterorout_record.fz
     *
     * @mbggenerated
     */
    private Integer fz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjc_enterorout_record.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjc_enterorout_record.Order_num
     *
     * @return the value of hjc_enterorout_record.Order_num
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjc_enterorout_record.Order_num
     *
     * @param orderNum the value for hjc_enterorout_record.Order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjc_enterorout_record.Car_number
     *
     * @return the value of hjc_enterorout_record.Car_number
     *
     * @mbggenerated
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjc_enterorout_record.Car_number
     *
     * @param carNumber the value for hjc_enterorout_record.Car_number
     *
     * @mbggenerated
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjc_enterorout_record.Enter_or_Out
     *
     * @return the value of hjc_enterorout_record.Enter_or_Out
     *
     * @mbggenerated
     */
    public Integer getEnterOrOut() {
        return enterOrOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjc_enterorout_record.Enter_or_Out
     *
     * @param enterOrOut the value for hjc_enterorout_record.Enter_or_Out
     *
     * @mbggenerated
     */
    public void setEnterOrOut(Integer enterOrOut) {
        this.enterOrOut = enterOrOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjc_enterorout_record.Enter_time
     *
     * @return the value of hjc_enterorout_record.Enter_time
     *
     * @mbggenerated
     */
    public Date getEnterTime() {
        return enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjc_enterorout_record.Enter_time
     *
     * @param enterTime the value for hjc_enterorout_record.Enter_time
     *
     * @mbggenerated
     */
    public void setEnterTime(Date enterTime) {
        this.enterTime = enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjc_enterorout_record.Out_time
     *
     * @return the value of hjc_enterorout_record.Out_time
     *
     * @mbggenerated
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjc_enterorout_record.Out_time
     *
     * @param outTime the value for hjc_enterorout_record.Out_time
     *
     * @mbggenerated
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjc_enterorout_record.Price
     *
     * @return the value of hjc_enterorout_record.Price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjc_enterorout_record.Price
     *
     * @param price the value for hjc_enterorout_record.Price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjc_enterorout_record.fz
     *
     * @return the value of hjc_enterorout_record.fz
     *
     * @mbggenerated
     */
    public Integer getFz() {
        return fz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjc_enterorout_record.fz
     *
     * @param fz the value for hjc_enterorout_record.fz
     *
     * @mbggenerated
     */
    public void setFz(Integer fz) {
        this.fz = fz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjc_enterorout_record.msg
     *
     * @return the value of hjc_enterorout_record.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjc_enterorout_record.msg
     *
     * @param msg the value for hjc_enterorout_record.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}