package xd.fw.bean;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade.right_count
     *
     * @mbggenerated
     */
    private Integer rightCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade.fail_count
     *
     * @mbggenerated
     */
    private Integer failCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade.user_name
     *
     * @return the value of t_grade.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade.user_name
     *
     * @param userName the value for t_grade.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade.city
     *
     * @return the value of t_grade.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade.city
     *
     * @param city the value for t_grade.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade.right_count
     *
     * @return the value of t_grade.right_count
     *
     * @mbggenerated
     */
    public Integer getRightCount() {
        return rightCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade.right_count
     *
     * @param rightCount the value for t_grade.right_count
     *
     * @mbggenerated
     */
    public void setRightCount(Integer rightCount) {
        this.rightCount = rightCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade.fail_count
     *
     * @return the value of t_grade.fail_count
     *
     * @mbggenerated
     */
    public Integer getFailCount() {
        return failCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade.fail_count
     *
     * @param failCount the value for t_grade.fail_count
     *
     * @mbggenerated
     */
    public void setFailCount(Integer failCount) {
        this.failCount = failCount;
    }
}