package xd.fw.bean;

import java.util.Date;

public class ImportDzRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_dz_record.year
     *
     * @mbggenerated
     */
    private Short year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_dz_record.month
     *
     * @mbggenerated
     */
    private Short month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_dz_record.notification
     *
     * @mbggenerated
     */
    private String notification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_dz_record.import_date
     *
     * @mbggenerated
     */
    private Date importDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_dz_record.year
     *
     * @return the value of t_import_dz_record.year
     *
     * @mbggenerated
     */
    public Short getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_dz_record.year
     *
     * @param year the value for t_import_dz_record.year
     *
     * @mbggenerated
     */
    public void setYear(Short year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_dz_record.month
     *
     * @return the value of t_import_dz_record.month
     *
     * @mbggenerated
     */
    public Short getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_dz_record.month
     *
     * @param month the value for t_import_dz_record.month
     *
     * @mbggenerated
     */
    public void setMonth(Short month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_dz_record.notification
     *
     * @return the value of t_import_dz_record.notification
     *
     * @mbggenerated
     */
    public String getNotification() {
        return notification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_dz_record.notification
     *
     * @param notification the value for t_import_dz_record.notification
     *
     * @mbggenerated
     */
    public void setNotification(String notification) {
        this.notification = notification == null ? null : notification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_dz_record.import_date
     *
     * @return the value of t_import_dz_record.import_date
     *
     * @mbggenerated
     */
    public Date getImportDate() {
        return importDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_dz_record.import_date
     *
     * @param importDate the value for t_import_dz_record.import_date
     *
     * @mbggenerated
     */
    public void setImportDate(Date importDate) {
        this.importDate = importDate;
    }

    public ImportDzRecord(){}
    public ImportDzRecord(int year, int month) {
        this.year = (short)year;
        this.month = (short)month;
        this.importDate = new Date();
        this.notification = "N";
    }
}