package xd.fw.bean;

public class PrimaryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_primary_key.table_name
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_primary_key.current_id
     *
     * @mbggenerated
     */
    private Integer currentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_primary_key.table_name
     *
     * @return the value of t_primary_key.table_name
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_primary_key.table_name
     *
     * @param tableName the value for t_primary_key.table_name
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_primary_key.current_id
     *
     * @return the value of t_primary_key.current_id
     *
     * @mbggenerated
     */
    public Integer getCurrentId() {
        return currentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_primary_key.current_id
     *
     * @param currentId the value for t_primary_key.current_id
     *
     * @mbggenerated
     */
    public void setCurrentId(Integer currentId) {
        this.currentId = currentId;
    }

    public PrimaryKey(String tableName, int currentId) {
        this.tableName = tableName;
        this.currentId = currentId;
    }
    public PrimaryKey(){}
}