package xd.fw.bean;

public class Userdz {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_userdz.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_userdz.user_name
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_userdz.wxid
	 * @mbggenerated
	 */
	private String wxid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_userdz.phone
	 * @return  the value of t_userdz.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_userdz.phone
	 * @param phone  the value for t_userdz.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_userdz.user_name
	 * @return  the value of t_userdz.user_name
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_userdz.user_name
	 * @param userName  the value for t_userdz.user_name
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_userdz.wxid
	 * @return  the value of t_userdz.wxid
	 * @mbggenerated
	 */
	public String getWxid() {
		return wxid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_userdz.wxid
	 * @param wxid  the value for t_userdz.wxid
	 * @mbggenerated
	 */
	public void setWxid(String wxid) {
		this.wxid = wxid == null ? null : wxid.trim();
	}

	public Userdz(){}
	public Userdz(String phone, String wxid) {
		this.phone = phone;
		this.wxid = wxid;
	}
}