package xd.fw.bean;

import java.util.Date;

public class UserValidate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_validate.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_validate.validate_code
	 * @mbggenerated
	 */
	private String validateCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_validate.status
	 * @mbggenerated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_validate.validate_time
	 * @mbggenerated
	 */
	private Date validateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_validate.phone
	 * @return  the value of t_user_validate.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_validate.phone
	 * @param phone  the value for t_user_validate.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_validate.validate_code
	 * @return  the value of t_user_validate.validate_code
	 * @mbggenerated
	 */
	public String getValidateCode() {
		return validateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_validate.validate_code
	 * @param validateCode  the value for t_user_validate.validate_code
	 * @mbggenerated
	 */
	public void setValidateCode(String validateCode) {
		this.validateCode = validateCode == null ? null : validateCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_validate.status
	 * @return  the value of t_user_validate.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_validate.status
	 * @param status  the value for t_user_validate.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_validate.validate_time
	 * @return  the value of t_user_validate.validate_time
	 * @mbggenerated
	 */
	public Date getValidateTime() {
		return validateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_validate.validate_time
	 * @param validateTime  the value for t_user_validate.validate_time
	 * @mbggenerated
	 */
	public void setValidateTime(Date validateTime) {
		this.validateTime = validateTime;
	}

	public static final String WAIT = "W", SENDED = "S", ERROR= "E";
	public UserValidate(){}

	public UserValidate(String phone, String validateCode) {
		this.phone = phone;
		this.validateCode = validateCode;
		this.status = WAIT;
		this.validateTime = new Date();
	}
}