package xd.fw.bean;

import org.apache.commons.lang3.StringUtils;

public class UserCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.business
     *
     * @mbggenerated
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.wx_contract_name1
     *
     * @mbggenerated
     */
    private String wxContractName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.wx_contract_phone1
     *
     * @mbggenerated
     */
    private String wxContractPhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.wx_contract_name2
     *
     * @mbggenerated
     */
    private String wxContractName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.wx_contract_phone2
     *
     * @mbggenerated
     */
    private String wxContractPhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.manager_name
     *
     * @mbggenerated
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.remark_content
     *
     * @mbggenerated
     */
    private String remarkContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_company.credit_scope
     *
     * @mbggenerated
     */
    private String creditScope;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.code
     *
     * @return the value of t_user_company.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.code
     *
     * @param code the value for t_user_company.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.company_name
     *
     * @return the value of t_user_company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.company_name
     *
     * @param companyName the value for t_user_company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.area
     *
     * @return the value of t_user_company.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.area
     *
     * @param area the value for t_user_company.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.business
     *
     * @return the value of t_user_company.business
     *
     * @mbggenerated
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.business
     *
     * @param business the value for t_user_company.business
     *
     * @mbggenerated
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.wx_contract_name1
     *
     * @return the value of t_user_company.wx_contract_name1
     *
     * @mbggenerated
     */
    public String getWxContractName1() {
        return wxContractName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.wx_contract_name1
     *
     * @param wxContractName1 the value for t_user_company.wx_contract_name1
     *
     * @mbggenerated
     */
    public void setWxContractName1(String wxContractName1) {
        this.wxContractName1 = wxContractName1 == null ? null : wxContractName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.wx_contract_phone1
     *
     * @return the value of t_user_company.wx_contract_phone1
     *
     * @mbggenerated
     */
    public String getWxContractPhone1() {
        return wxContractPhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.wx_contract_phone1
     *
     * @param wxContractPhone1 the value for t_user_company.wx_contract_phone1
     *
     * @mbggenerated
     */
    public void setWxContractPhone1(String wxContractPhone1) {
        this.wxContractPhone1 = wxContractPhone1 == null ? null : wxContractPhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.wx_contract_name2
     *
     * @return the value of t_user_company.wx_contract_name2
     *
     * @mbggenerated
     */
    public String getWxContractName2() {
        return wxContractName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.wx_contract_name2
     *
     * @param wxContractName2 the value for t_user_company.wx_contract_name2
     *
     * @mbggenerated
     */
    public void setWxContractName2(String wxContractName2) {
        this.wxContractName2 = wxContractName2 == null ? null : wxContractName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.wx_contract_phone2
     *
     * @return the value of t_user_company.wx_contract_phone2
     *
     * @mbggenerated
     */
    public String getWxContractPhone2() {
        return wxContractPhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.wx_contract_phone2
     *
     * @param wxContractPhone2 the value for t_user_company.wx_contract_phone2
     *
     * @mbggenerated
     */
    public void setWxContractPhone2(String wxContractPhone2) {
        this.wxContractPhone2 = wxContractPhone2 == null ? null : wxContractPhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.manager_name
     *
     * @return the value of t_user_company.manager_name
     *
     * @mbggenerated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.manager_name
     *
     * @param managerName the value for t_user_company.manager_name
     *
     * @mbggenerated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.remark_content
     *
     * @return the value of t_user_company.remark_content
     *
     * @mbggenerated
     */
    public String getRemarkContent() {
        return remarkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.remark_content
     *
     * @param remarkContent the value for t_user_company.remark_content
     *
     * @mbggenerated
     */
    public void setRemarkContent(String remarkContent) {
        this.remarkContent = remarkContent == null ? null : remarkContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_company.credit_scope
     *
     * @return the value of t_user_company.credit_scope
     *
     * @mbggenerated
     */
    public String getCreditScope() {
        return creditScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_company.credit_scope
     *
     * @param creditScope the value for t_user_company.credit_scope
     *
     * @mbggenerated
     */
    public void setCreditScope(String creditScope) {
        this.creditScope = creditScope == null ? null : creditScope.trim();
    }

    String phone;

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhone() {
        return phone;
    }

    public String getWxPhone(){
        if (StringUtils.isNotBlank(wxContractPhone1)){
            return wxContractPhone1;
        }
        if (StringUtils.isNotBlank(wxContractPhone2)){
            return wxContractPhone2;
        }
        return null;
    }
    public String getWxName(){
        if (StringUtils.isNotBlank(wxContractName1)){
            return wxContractName1;
        }
        if (StringUtils.isNotBlank(wxContractName2)){
            return wxContractName2;
        }
        return null;
    }
}